### ISSUE TITLE
Certificate import error.

### ISSUE THREAD

**Issue by vivekbhatia14** [HewlettPackard/ilo-chef#15]
```ruby
ilo_https_cert 'import certificate' do
  ilo ilo1
  certificate cert
  action :import
  not_if { valid || cert.nil? }
end
```
 
The above block does not work as the error as no "cert" function.

NoMethodError
-------------
undefined method `cert' for IloCookbook::HTTPSCert

**Comment by jsmartt** [comment]
@vivekbhatia14 , `cert` is actually a user-supplied variable.

In the [README](https://github.com/HewlettPackard/ilo-chef#ilo_https_cert), directly above the block you coppied above, it says:

```ruby
# Here you'll need to have a step that submits the CSR to a certificate authority
# (or self-signs it) and gets back the signed certificate. It will look something like:
# -----BEGIN CERTIFICATE-----
# lines_of_secret_text
# -----END CERTIFICATE-----
# For this example, we're assuming we've read in the content of the certificate to the
# "cert" variable (as a string).
```

Basically, there's 3 steps for creating a new cert:
 1. Generate a certificate signing request (CSR).
 2. Sign the CSR with a certificate authority (CA), producing a new cert.
 3. Upload the new cert to the iLO.

However, we have no way of doing step 2. That step must be filled in by the user, according to their company's certificate signing process.

However, for the sake of making a complete example in the README, I think we could add in some example code that signs the CSR with an arbitrarily-generated CA. The user will still have to replace that section.

Thoughts?

**Comment by Anirudh-Gupta** [comment]
ReadMe contains the updated example usage. Hence closing it.
