### ISSUE TITLE
ChangePassword does not work

### ISSUE THREAD

**Issue by vivekbhatia14** [HewlettPackard/ilo-chef#17]
Looks like the change password feature has been forgotten or removed in the new version of ilo cookbook.

**Comment by jsmartt** [comment]
The [:ilo_account_service](https://github.com/HewlettPackard/ilo-chef/blob/master/libraries/account_service.rb) resource has been deprecated in favor of the [:ilo_user](https://github.com/HewlettPackard/ilo-chef/blob/master/libraries/user.rb#L29) resource. This new resource has a :create action that will create the user, set their permissions, and set their password all in 1 resource. No need for separate create and update_password actions.

Please see the [README](https://github.com/HewlettPackard/ilo-chef#ilo_user) for usage.

**Comment by vivekbhatia14** [comment]
There is a need as user account password on ILO has to be changed on regular basis(monthly, quaterly, yearly based on company policies).

**Comment by jsmartt** [comment]
@vivekbhatia14, that can easily be done with the ilo_user resource. All you have to do is update the password parameter and it will get set on the iLO. The real difference here is that the update_password action does ONLY that; so the creation and updates are separated into multiple resources. In contrast the ilo_user resource allows you to create the user (and set their initial password and permissions), **as well as** update them later on.

Take a look at the [Chef user resource](https://docs.chef.io/resource_user.html). You declare the user, the associated groups, password, etc. all in 1 resource. Then anytime you want to change that user's groups, passwords, etc, you just update that resource and it makes those changes when it converges. You wouldn't want to have to create a separate resource to update the user's password later on, and yet another to update the groups. The exact same principles apply to our iLO users.

The ilo_user resource meets the need you stated above, so are we ready to close this issue?

**Comment by vivekbhatia14** [comment]
@jsmartt can you put an working example of changing password in the readme file?

**Comment by jsmartt** [comment]
@vivekbhatia14 , the example in the README [here](https://github.com/HewlettPackard/ilo-chef#ilo_user) is the same as an example that I would create. Let's say a user ("bob") exists on the iLO, but we want to start using Chef to manage bob. I would add this to my recipe:

```ruby
ilo_user 'creater user' do
  ilos [ilo1, ilo2]
  username 'bob'
  password 'password123'
  login_priv true
  remote_console_priv false
  user_config_priv true
  virtual_media_priv false
  virtual_power_and_reset_priv true
  ilo_config_priv false
end
```

Now whenever Chef runs, it will ensure that the user "bob" exists, his password is "password123", and his privileges are set as I defined them.

Let's say that 3 months down the road, I want to change bob's password. All I have to do is update that same resource in my recipe. Now I have:

```ruby
ilo_user 'creater user' do
  ilos [ilo1, ilo2]
  username 'bob'
  password 'new_password456'    # THIS IS THE ONLY THING THAT CHANGED
  login_priv true
  remote_console_priv false
  user_config_priv true
  virtual_media_priv false
  virtual_power_and_reset_priv true
  ilo_config_priv false
end
```

**Comment by vivekbhatia14** [comment]
Updated README file with example
