### ISSUE TITLE
Setting/modifying iLo user permissions

### ISSUE THREAD

**Issue by kreyno96it** [HewlettPackard/ilo-chef#7]
First, I want to thank everyone for their great work on this, adding iLo configuration to chef really helps speed up build time for a new server.

First I want to say I'm very new to chef and ruby.  I was looking at the examples and I see creating a user and changing a user's password is supported but I don't see a way to set or modify user permissions, is that supported yet?

Thanks.

**Comment by jsmartt** [comment]
Hi @kreyno96it , we're glad you're finding it useful. Your observation is correct. It's not currently supported, but we have identified it as a feature to be added. We're open to your contributions, but we're planning on implementing it in the near future if someone doesn't  beat us to it.

**Comment by jsmartt** [comment]
@kreyno96it, there's a new `ilo_user` resource that handles this now. Take a look!
