### ISSUE TITLE
Setting/modifying BIOS settings

### ISSUE THREAD

**Issue by kreyno96it** [HewlettPackard/ilo-chef#8]
We have a need to modify several default BIOS settings when building a new server.  We are currently using the hprest command to do this but would like to have chef do this instead.   Can support for modifying BIOS settings be added to this cookbook? 

Here is an example of a few BIOS settings we change from default;
PowerProfile MaxPerf
PowerRegulator StaticHighPerf
ProcHyperthreading Disabled
ProcNoExecute Enabled
ProcTurbo Disabled
ProcVirtualization Disabled

Thanks.

**Comment by bikbajwa** [comment]
Hey @kreyno96it, yes we can certainly add these settings. We will implement them into the existing ilo_bios resource.
